export const CHANGE_STATUS_HEATUP = "CHANGE_STATUS_HEATUP";
export const CHANGE_STATUS_ASSESMENT = "CHANGE_STATUS_ASSESMENT";
export const CHANGE_STATUS_TRAINING = "CHANGE_STATUS_TRAINING";
export const SET_TIMER_STARTED = "SET_TIMER_STARTED";
export const SET_TIMER_PAUSED = "SET_TIMER_PAUSED";
export const SET_TIMER_RESUMED = "SET_TIMER_RESUMED";
export const SET_TIMER_STOPPED = "SET_TIMER_STOPPED";